-- TOP IMPORTER OF EACH COMMODITY

WITH CTE AS(SELECT PC_CODE, Commodity, Country,Trade_Value_USD, RANK() OVER (PARTITION BY COMMODITY ORDER BY Trade_Value_USD DESC) AS 'RAN' FROM fy25)

SELECT PC_CODE, COMMODITY, COUNTRY, round(TRADE_VALUE_USD/1000000,0) AS 'Million USD' FROM CTE WHERE RAN = 1 ORDER BY 4  DESC