-- TOP IMPORTER OF EACH COMMODITY

WITH CTE AS(SELECT PC_CODE, Commodity, Continent,SUM(Trade_Value_USD) OVER (PARTITION BY Continent,Commodity) AS  TRADE, RANK() OVER (PARTITION BY Continent ORDER BY Trade_Value_USD DESC) AS 'RAN' FROM fy25)

SELECT CONTINENT, PC_CODE, COMMODITY, round(TRADE/1000000,0) AS 'Million USD' FROM CTE WHERE RAN = 1 AND CONTINENT NOT IN ('UNSPECIFIED','INTERNATIONAL WATERS') ORDER BY 4  DESC