-- TOP IMPORT OF EACH COUNTRY

WITH CTE AS(SELECT  Commodity, Country,Trade_Value_USD, RANK() OVER (PARTITION BY Country ORDER BY Trade_Value_USD DESC) AS 'RAN' FROM fy25)

SELECT  COUNTRY, COMMODITY, round(TRADE_VALUE_USD/1000000,0) AS 'Million USD' FROM CTE WHERE RAN = 1 ORDER BY 3  DESC