-- TOP IMPORT OF EACH COUNTRY

WITH CTE AS(SELECT  CONTINENT, Country,SUM(Trade_Value_USD) OVER (PARTITION BY Continent,COUNTRY) AS  TRADE, RANK() OVER (PARTITION BY CONTINENT ORDER BY Trade_Value_USD DESC) AS 'RAN' FROM fy25)

SELECT CONTINENT, COUNTRY, round(TRADE/1000000,0) AS 'Million USD' FROM CTE WHERE RAN = 1 ORDER BY 3  DESC